name: rune
description: "The rune player."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.1008

environment:
  sdk: ">=3.8.1 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  fluent_ui:
    git:
      url: https://github.com/Losses/fluent_ui.git
      ref: fa35f8cae87d2c0a9989279fe99fdee32d601e84
  flutter_acrylic: ^1.1.4
  system_theme: 3.1.2
  provider: ^6.1.2
  url_launcher: ^6.3.0
  mesh_gradient: ^1.3.7
  infinite_scroll_pagination: ^4.0.0
  material_symbols_icons: ^4.2771.0
  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.3
  path: ^1.9.0
  crypto: ^3.0.6
  crclib: ^3.0.0
  reorderables: ^0.6.0
  material_color_utilities: ^0.11.1
  get_storage: ^2.1.1
  hashlib: ^1.19.2
  rxdart: ^0.28.0
  flutter_shaders: ^0.1.2
  flip_card: ^0.7.0
  flutter_boring_avatars: ^2.0.1
  logger: ^2.4.0
  flutter_svg: ^2.0.10+1
  rinf: ^8.7.1
  tuple: ^2.0.2
  meta: ^1.15.0
  very_good_infinite_list: ^0.9.0
  flutter_fullscreen: ^1.0.1
  device_info_plus: ^11.1.1
  macos_secure_bookmarks:
    git:
      url: https://github.com/XMLHexagram/macos_secure_bookmarks.git
      ref: c07abbf7c186c543de09a9c7df8577bbf5e27748
  permission_handler: ^11.3.1
  animated_flip_counter: ^0.3.4
  intl: ^0.20.2
  bitsdojo_window: ^0.1.6
  flutter_window_close: ^1.2.0
  flutter_staggered_grid_view: ^0.7.0
  local_notifier: ^0.1.6
  system_tray:
    git:
      url: https://github.com/Losses/system_tray.git
      ref: ddbf360835b1db404fbd52b07b250e0e2c950266
  scrollable_positioned_list:
    git:
      url: https://github.com/Losses/scrollable_positioned_list.git
      ref: 0ec616519c68ff004c014a6907ff04d2cba43b7f
  desktop_drop: ^0.5.0
  uuid: ^3.0.7
  pointycastle: ^3.9.1
  collection: ^1.18.0
  clipboard: ^0.1.3
  asn1lib: ^1.5.8
  badges: ^3.1.2
  fast_file_picker: ^0.4.7
  file_selector: ^1.0.3
  vector_math: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  msix: ^3.16.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: false

  shaders:
    - lib/shaders/gradient.frag
    - lib/shaders/lens_flare.frag

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/arrow-circle-left-solid.svg
    - assets/mono_color_logo.svg
    - assets/device-layer-1.svg
    - assets/device-layer-2.svg
    - assets/device-layer-3.svg
    - assets/box.svg
    - assets/disk-color.svg
    - assets/disk-border.svg
    - assets/disk-center.svg
    - assets/branding-text.svg
    - assets/startup_0.ogg
    - assets/startup_1.ogg
    - assets/linux-tray-dark.svg
    - assets/linux-tray-light.svg
    - assets/mac-tray.svg
    - assets/tray_icon_light.ico
    - assets/tray_icon_dark.ico
    - assets/watermark.png
    - assets/bandcamp.svg
    - assets/itch.svg

  fonts:
    - family: NotoRunic
      fonts:
        - asset: assets/NotoSansRunic-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

msix_config:
  display_name: Rune Player
  publisher_display_name: Losses Don
  identity_name: 23662LossesDon.RunePlayer
  publisher: CN=16FBEDB1-15BD-44BA-B4B4-FF0448A66E6C
  msix_version: 2.0.1008.0
  store: true
  capabilities: removableStorage
  logo_path: ./assets/source/microsoft_store/installer_icon.png
  debug: false

rinf:
  gen_output_dir: lib/bindings
