[package]
name = "lyric"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "lyric"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.98"
log = "0.4.22"
once_cell = "1.20.2"
regex = "1.11.1"
subtp = "0.2.0"
xmltree = "0.11.0"
