name: Lint

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
  rust-analyze:
    name: Rust Analyze
    runs-on: ubuntu-latest
    
    steps: 
      - name: Check Out
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Flutter Toolchain
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y liblmdb0 jq alsa-base alsa-source librust-alsa-sys-dev libasound2-dev liblmdb-dev clang cmake ninja-build pkg-config libgtk-3-dev dpkg-dev libayatana-appindicator3-dev libnotify-dev

      - uses: Swatinem/rust-cache@v2

      - name: Install the Rust dependencies
        run: cargo install rinf_cli

      - name: Flutter pub get
        run: flutter pub get

      - name: Generate message files
        run: rinf gen

      - name: Format message files
        run: |
          shopt -s globstar
          cargo fmt -- native/hub/src/messages/**/*.rs

      - name: Run cargo fmt
        run: cargo fmt -- --check
      
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  flutter-analyze:
    name: Flutter Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Flutter Toolchain
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Install the Rust dependencies
        run: cargo install rinf_cli

      - name: Flutter pub get
        run: flutter pub get

      - name: Generate message files
        run: rinf gen
      
      - name: Analyze Flutter
        run: |
          flutter analyze .

      - name: Dart Flutter
        run: |
          dart analyze .

      


